mdq-back/mdq/urls.py
from django.urls import path, include
from django.contrib import admin
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from mdq.views import auth, pages, shop
from mdq.rest_views import viewsets, rest_views

router = DefaultRouter()
router.register(r"petselect", viewsets.PetTypeViewSet, basename="petselect")
router.register(r"pet", viewsets.PetViewSet, basename="pet")

urlpatterns = [
    # api
    path('api/v1/', include(router.urls)),
    path('api/v1/register', rest_views.user_registration, name='register'),
    path('api/v1/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # api task
    path('api/v1/tasks/select/', viewsets.TaskSelectAPIView.as_view(), name="task-select"),
    path('api/v1/tasks/create/', viewsets.TaskCreateAPIView.as_view(), name="task-create"),
    path('api/v1/tasks/list/', viewsets.TaskListAPIView.as_view(), name="task-list"),
    path('api/v1/tasks/<int:task_id>/complete/', viewsets.TaskCompleteAPIView.as_view(), name="task-complete"),
    # api adventure
    path('api/v1/adventure/locations/', viewsets.AdventureLocationAPIListView.as_view(), name="adv-location"),
    path('api/v1/adventure/current/', viewsets.CurrentAdventureAPIView.as_view(), name="current-adv"),
    path('api/v1/adventure/start/', viewsets.AdventureStartAPIView.as_view(), name="adv-start"),
    path('api/v1/adventure/complete/<int:pk>/', viewsets.CompleteAdventureAPIView.as_view(), name="adv-complete"),
    # api shop
    path('api/v1/shop/', viewsets.ShopItemListView.as_view(), name="shop-display"),
    path('api/v1/shop/purchase/<int:item_id>/', viewsets.PurchaseItemAPIView.as_view(), name="shop-purchase"),
    path('api/v1/shop/history/', viewsets.PurchaseHistoryAPIView.as_view(), name="shop-history"),
    # api customize
    path('api/v1/customize/', viewsets.CustomizeAPIView.as_view(), name="customize-display"),
    path('api/v1/customize/equip/<int:clo_item_id>/', viewsets.EquipCosmeticAPIView.as_view(), name="customize-equip"),
    # non drf paths
    path('', auth.index, name='index'),
    path('pet/customization', pages.customize, name='customize'),
    path('pet/customization/equip/<int:clo_item_id>', pages.customize_equip, name='customize-equip'),
    path('pet/select', pages.petselect, name='petselect'),
    path('pet/select/<int:species_id>/', pages.petselectform, name='petselectform'),
    path('pet/shop', shop.shop, name='shop'),
    path('pet/shop/buy/<int:item_id>', shop.purchase_item, name="purchase-item"),
    path('pet/settings', pages.settings, name='settings'),
    path('pet/tasks', pages.task_list, name='tasklist'),
    path('pet/tasks/<int:task_id>/', pages.complete_task, name='task-complete'),
    path('pet/task_select', pages.task_select, name='task_select'),
    path('pet/create_task', pages.task_create, name='create-task'),
    path('pet/adventure', pages.adventure, name='adventure'),
    path('pet/adventure/complete/<int:current_id>', pages.complete_adventure, name='complete_adventure'),
    path('accounts/registration/', auth.register, name='register'),
    path('accounts/registration/termsandconditions', auth.termsandconditions, name='tos'),
]

mdq-back/system/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from turnstile.fields import TurnstileField


class XugarPasswordResetForm(PasswordResetForm):
    turnstile = TurnstileField()


class XugarPasswordResetView(PasswordResetView):
    form_class = XugarPasswordResetForm


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('accounts/password_reset/', XugarPasswordResetView.as_view(template_name="registration/password-reset.html")),
    path('accounts/password_reset/done/', PasswordResetDoneView.as_view(template_name="registration/password-reset-done.html")),
    path('accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name="registration/password-reset-change.html")),
    path('accounts/reset/done/', PasswordResetCompleteView.as_view(template_name="registration/password-reset-complete.html")),
    path('', include('mdq.urls')),
] + staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mdq-back/mdq/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser
from django.templatetags.static import static
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

class MdqUser(AbstractUser):
    pass


class Profile(models.Model):
    user = models.OneToOneField(MdqUser, on_delete=models.CASCADE)
    avatar = models.ImageField(blank=True, upload_to='avatar')
    birth = models.DateField(null=True, blank=True, default=None)
    birthday = models.DateTimeField(auto_now_add=True)

    def get_avatar_url(self, request=None):
        url = static('img/placeholder/300x150.png')
        avatar_url = self.avatar.url if self.avatar else url
        return request.build_absolute_uri(avatar_url) if request else avatar_url

    def __str__(self) -> str:
        return f"{self.user}"


class PetType(models.Model):
    species = models.CharField(max_length=50)
    desc = models.TextField(max_length=300, blank=True)
    pet_avatar = models.ImageField(upload_to='pets/')

    def __str__(self):
        return self.species


class PetBackground(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="pet_backgrounds/")
    description = models.TextField(max_length=300, blank=True)

    def __str__(self):
        return self.name


class Pet(models.Model):
    user = models.OneToOneField(MdqUser, on_delete=models.CASCADE)
    species = models.ForeignKey(PetType, on_delete=models.CASCADE)
    background = models.ForeignKey(PetBackground, default=1, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, default="Pet")
    exp = models.FloatField(default=0.0)
    hp = models.PositiveIntegerField(default=20)
    stamina = models.PositiveIntegerField(default=40)
    bond = models.FloatField(default=0.0)
    mood = models.IntegerField(default=50)
    birthday = models.DateTimeField(auto_now_add=True)
    last_fed = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.name} - ({self.species.species})"

    def get_level(self):
        level = 1
        while self.exp >= self.exp_required(level + 1):
            level += 1
        return level

    def exp_required(self, x):
        b, t = 1, 0
        return (1 + b) ** (x + t)

    @property
    def mood_status(self):
        if self.mood >= 100:
            return "Perfect"
        if self.mood >= 80:
            return "Good"
        if self.mood >= 50:
            return "Normal"
        if self.mood >= 20:
            return "Bad"
        return "Awful"

    @property
    def bond_meter(self):
        if self.bond > 5:
            return round(self.bond / 20)
        return round(self.bond)

    @property
    def max_exp(self):
        return self.exp_required(self.get_level() + 1)

    @property
    def level(self):
        return self.get_level()

    @property
    def avatar(self):
        return self.species.pet_avatar.url


class Wallet(models.Model):
    user = models.OneToOneField(MdqUser, on_delete=models.CASCADE)
    credits = models.PositiveIntegerField(default=1000)
    pcredits = models.PositiveIntegerField(default=100)

    def __str__(self):
        return f"{self.user} - {self.credits} credits"


class Task(models.Model):
    user = models.ForeignKey(MdqUser, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    icon = models.CharField(max_length=50)
    custom = models.BooleanField(default=False)

    def __str__(self):
        if self.custom:
            return f"[Custom] {self.name} - ({self.user})"
        return f"[Default] {self.name}"


class TasksList(models.Model):
    user = models.OneToOneField(MdqUser, on_delete=models.CASCADE)
    tasks = models.ManyToManyField(Task, related_name="task_lists", blank=True)

    def __str__(self):
        return f"{self.user}'s Task List"


class AdventureLocation(models.Model):
    location_name = models.CharField(max_length=50)
    description = models.TextField(max_length=300, blank=True)
    difficulty = models.PositiveIntegerField(default=1)
    time = models.IntegerField(default=10)
    exp_reward = models.IntegerField(default=10)
    credit_reward = models.IntegerField(default=100)

    def __str__(self):
        return f"{self.location_name}"


class CurrentAdventure(models.Model):
    destination = models.ForeignKey(AdventureLocation, on_delete=models.CASCADE)
    user = models.OneToOneField(MdqUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} is adventuring in {self.destination.location_name}"


class Inventory(models.Model):
    user = models.OneToOneField(MdqUser, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user}'s Inventory"

    class Meta:
        verbose_name = "Inventory"
        verbose_name_plural = "Inventories"

class Consumable(models.Model):
    name = models.CharField(max_length=100)
    effect = models.TextField(max_length=50)
    uses = models.IntegerField(default=1)
    icon = models.ImageField(upload_to="consumable/")

    def __str__(self):
        return f"{self.name} (x{self.uses})"


class InventoryItem(models.Model):
    inventory = models.ForeignKey(Inventory, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    consumable = models.ForeignKey(Consumable, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.consumable.name} (x{self.quantity})"


class Cosmetic(models.Model):
    name = models.CharField(max_length=100)
    rarity = models.CharField(max_length=20)
    slot = models.CharField(max_length=50)
    icon = models.ImageField(upload_to="cosmetic/")

    def __str__(self):
        return f"{self.name} ({self.rarity})"


class Closet(models.Model):
    user = models.OneToOneField(MdqUser, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user}'s Closet"


class ClosetItem(models.Model):
    closet = models.ForeignKey(Closet, on_delete=models.CASCADE)
    cosmetic = models.ForeignKey(Cosmetic, on_delete=models.CASCADE)
    equipped = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.cosmetic} in {self.closet}"


class ShopItem(models.Model):
    name = models.CharField(max_length=50)
    price = models.IntegerField(default=100)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    item_object = GenericForeignKey("content_type", "object_id")

    def __str__(self):
        return f"{self.name} - {self.price} credits"


class CreditPurchase(models.Model):
    user = models.ForeignKey(MdqUser, on_delete=models.CASCADE)
    item = models.ForeignKey(ShopItem, on_delete=models.CASCADE)
    price = models.IntegerField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} bought {self.item.name}"


class PaymentTransaction(models.Model):
    user = models.ForeignKey(MdqUser, on_delete=models.CASCADE)
    amount = models.FloatField()
    payment_url = models.URLField(default='', blank=True)
    token = models.CharField(default='', blank=True, max_length=64)
    token_gp = models.DateTimeField(default=None, blank=True, null=True)
    paid = models.BooleanField(default=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    confirmed_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.user} - {self.paid}"

mdq-back/mdq/views/shop.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.contrib import messages

from mdq.models import ShopItem, CreditPurchase, Inventory, InventoryItem, Closet, ClosetItem, Wallet, Cosmetic

@login_required
def shop(request):
    items = ShopItem.objects.all()
    closet = Closet.objects.get(user=request.user)
    owned = ClosetItem.objects.filter(closet=closet).values_list("cosmetic_id", flat=True)
    return render(request, "pages/shop.html", {"items": items, 'owned': set(owned) })

@login_required
def purchase_item(request, item_id):
    balance = Wallet.objects.get(user=request.user)
    item = None

    try:
        item = ShopItem.objects.get(pk=item_id)
    except ShopItem.DoesNotExist:
        response = render(request, '404.html')
        response.status_code = 404
        return response

    if balance.credits < item.price:
        response = render(request, '404.html')
        response.status_code = 404
        return response

    balance.credits -= item.price
    balance.save()
    model = item.content_type.model_class()
    if model == Cosmetic:
        closet = Closet.objects.get(user=request.user)
        owned = ClosetItem.objects.filter(closet=closet, cosmetic=item.item_object).exists()

        if owned:
            messages.error(request, f"You already own this {item.item_object.name}!")
            return redirect("shop")
        ClosetItem.objects.create(closet=closet, cosmetic=item.item_object)
    else:
        inventory = Inventory.objects.get(user=request.user)

        try:
            inv_item = InventoryItem.objects.get(
                inventory=inventory,
                consumable=item.item_object
            )
            inv_item.quantity += 1
            inv_item.save()

        except InventoryItem.DoesNotExist:
            InventoryItem.objects.create(
                inventory=inventory,
                consumable=item.item_object,
                quantity=1
            )

    order = CreditPurchase.objects.create(
        user=request.user,
        item=item,
        price=item.price,
    )
    return redirect("shop")

mdq-back/mdq/templates/pages/customize.html
{% extends "layouts/master.html" %}
{% block content %}
{% load static %}

<body class="gamertext" style="background-image: url('{% static "backgrounds/background.png" %}')">
    <div class="container">
        <div class="d-flex justify-content-center align-items-center petscreen position-relative">
            <img class="h100 w100 img-fluid" src="{% static "backgrounds/boxpet.png" %}">
            <div class="pet-overlay position-absolute top-50 bottom-50 start-50 translate-middle">
                <div class="pet-wrapper position-relative d-inline-block">
                    <img class="img-fluid spot-offset" src="{% static 'icons/PETSPOT.png' %}">
                    <img class="pet img-fluid position-absolute top-50 start-50 translate-middle"
                    src="{{ pet.species.pet_avatar.url }}"
                    alt="{{ pet.name }}">
                </div>
            </div>
        </div>
    </div>
    <div class="container py-4">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <input type="text" class="form-control me-2" placeholder="Search items..." style="max-width: 70%;">
            <select class="form-select" style="max-width: 25%;">
                <option>All</option>
                <option>Cosmetics</option>
                <option>Consumables</option>
                <option>Backgrounds</option>
            </select>
        </div>
        <div class="row g-3 text-center">
        {% for closet in cosmetics %}
                {% for clo_item in closet.closetitem_set.all %}
                <div class="col-3">
                    <form method="post" action="{% url 'customize-equip' clo_item.id %}" class="equip-form">
                        {% csrf_token %}
                        <div class="inventory-slot d-flex flex-column justify-content-center align-items-center clickable-slot">
                            <img src="{{ clo_item.cosmetic.icon.url }}"
                                alt="{{ clo_item.cosmetic.name }}"
                                class="inventory-image">
                        </div>
                        <p class="small mb-0 text-wrap" style="color:black; overflow-wrap: break-word;">{{ clo_item.cosmetic.name }}</p>
                        {% if clo_item.equipped %}
                        <span class="badge bg-success mt-1 small">{{ clo_item.cosmetic.slot }}</span>
                        {% endif %}
                    </form>
                </div>
                {% endfor %}
            {% endfor %}
            {% for inventory in items %}
                {% for inv_item in inventory.inventoryitem_set.all %}
                <div class="col-3">
                    <div class="inventory-slot d-flex justify-content-center align-items-center text-wrap">
                        <img src="{{ inv_item.consumable.icon.url }}" alt="{{ inv_item.consumable.name }}" class="inventory-image">
                    </div>
                    <div class="small">
                        <p class="text-wrap" style="color:black; overflow-wrap: break-word;">{{ inv_item.consumable.name  }}</p>
                        <p style="color:black;">x{{ inv_item.quantity }}</p>
                    </div>
                </div>
                {% endfor %}
            {% endfor %}
        </div>
    </div>
</body>
<script>
    document.querySelectorAll(".clickable-slot").forEach(slot => {
        slot.addEventListener("click", function() {
            this.closest(".equip-form").submit();
        });
    });
</script>
{% endblock %}

mdq-back/mdq/templates/pages/pet_select.html
{% extends "layouts/master.html" %}
{% block content %}
{% load static %}
<body class="gamertext" style="background-image: url('{% static "backgrounds/background.png" %}')">
    <div class="container d-flex flex-column justify-content-center align-items-center min-vh-100">
        <div class="d-flex align-items-center justify-content-start custom-card">
            <div class="circle-wrapper d-flex align-items-center justify-content-center">
                <img src="{{ pet.pet_avatar.url }}" alt="{{ pet.species }}" class="circle-img">
            </div>
            <div class="text-box flex-grow-1">
                <a class="w-100 h-100 biggertext" href="{% url 'petselectform' pet.id %}">
                    <div class="biggertext">
                        {{ pet.species }}
                    </div>
                </a>
                <hr class="divider">
                <div class="smallertext">{{ pet.desc }}</div>
            </div>
        </div>
        <div class="d-flex align-items-center justify-content-start custom-card">
            <div class="circle-wrapper d-flex align-items-center justify-content-center">
                <img src="{{ pet2.pet_avatar.url }}" alt="{{ pet2.species }}" class="circle-img">
            </div>
            <div class="text-box flex-grow-1">
                <a class="w-100 h-100 biggertext" href="{% url 'petselectform' pet2.id %}">
                    <div class="biggertext">
                        {{ pet2.species }}
                    </div>
                </a>                <hr class="divider">
                <div class="smallertext">{{ pet2.desc }}</div>
            </div>
        </div>
        <div class="d-flex align-items-center justify-content-start custom-card">
            <div class="circle-wrapper d-flex align-items-center justify-content-center">
                <img src="{{ pet3.pet_avatar.url }}" alt="{{ pet3.species }}" class="circle-img">
            </div>
            <div class="text-box flex-grow-1">
                <a class="w-100 h-100 biggertext" href="{% url 'petselectform' pet3.id %}">
                    <div class="biggertext">
                        {{ pet3.species }}
                    </div>
                </a>                <hr class="divider">
                <div class="smallertext">{{ pet3.desc }}</div>
            </div>
        </div>
    </div>
</body>
{% endblock %}

mdq-back/mdq/templates/pages/pet_select_form.html
{% extends "layouts/master.html" %}
{% block content %}
{% load django_bootstrap5 %}
{% load static %}

<body class="gamertext" style="background-image: url('{% static "backgrounds/background.png" %}')">
    <div class="container">
        <div class="d-flex justify-content-center align-items-center petscreen">
            <form method="post" class="w100 h100">
                {% csrf_token %}
                <div class="card mt-auto d-flex w-100 h-100 d-flex justify-content-center text-center" style="background-color: #9b5862ff;">
                    <img class="card-img-top w-100 circle" src="{{ species.pet_avatar.url }}" alt="pet" />
                    <div class="card-header">
                        <h4 class="card-title">{{ species.species }}</h4>
                    </div>
                    <div class="card-body h-100" style="background-color: #be6b77ff;">
                        {% bootstrap_form form %}
                    </div>
                    <div class="card-footer d-flex justify-content-center">
                        <button class="btn" style="background-color: #bd4d5dff;" type="submit">welcome your new friend!</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</body>
{% endblock %}

mdq-back/mdq/templates/pages/shop.html
{% extends "layouts/master.html" %}
{% block content %}
{% load static %}
<body class="gamertext" style="background-image: url('{% static "backgrounds/background.png" %}')">
    <div class="container">
        <div class="d-flex justify-content-center align-items-center petscreen position-relative">
            <img class="h100 w100 img-fluid" src="{% static "backgrounds/boxpet.png" %}">
        </div>
    </div>
    <div class="container py-4">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <input type="text" class="form-control me-2" placeholder="Search items..." style="max-width: 70%;">
            <select class="form-select" style="max-width: 25%;">
                <option>All</option>
                <option>Cosmetics</option>
                <option>Consumables</option>
                <option>Backgrounds</option>
            </select>
        </div>
        <div class="row g-3">
            {% for item in items %}
                <div class="col-3">
                    <div class="inventory-slot d-flex justify-content-center align-items-center">
                        <img src="{{ item.item_object.icon.url }}" alt="item" class="inventory-image">
                    </div>
                    <div class="small text-center">
                        {% if item.content_type.model == "cosmetic" and item.item_object.id in owned %}
                            <p style="color:gray;">{{ item.item_object.name }}</p>
                            <span class="badge bg-success">✔ Owned</span>
                        {% else %}
                            <a href="{% url 'purchase-item' item.id %}"
                            class="purchase-link" data-name="{{ item.item_object.name }}" data-price="{{ item.price }}">
                                <p class="text-wrap" style="color:black; overflow-wrap: break-word;">{{ item.item_object.name }}</p>
                            </a>
                            <p style="color:black;" class="fw-light fst-italic">${{ item.price }}</p>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</body>
<script>
    document.querySelectorAll(".purchase-link").forEach(link => {
        link.addEventListener("click", function(event) {
            event.preventDefault();

            const itemName = this.dataset.name;
            const itemPrice = this.dataset.price;
            const url = this.href;

            if (confirm(`Do you want to buy "${itemName}" for $${itemPrice} credits?`)) {
                window.location.href = url;
            }
        });
    });
</script>

{% endblock %}